/* Generates frontend/config.js from environment variables - run at build time.
 *
 *   Cloudflare Pages: set API_BASE_URL + ACCESS_KEY in the dashboard
 *   (Settings -> Environment variables), build command:
 *       node frontend/build-config.js
 *   output directory: frontend
 *
 *   Local dev: just run `node frontend/build-config.js` once (it reads
 *   ACCESS_KEY from ../.env automatically; API_BASE_URL defaults to ""
 *   which means same-origin).
 *
 * config.js is gitignored - secrets never enter the repo.
 */
const fs = require("fs");
const path = require("path");

function valueFromDotenv(name) {
  try {
    const text = fs.readFileSync(path.join(__dirname, "..", ".env"), "utf8");
    const m = text.match(new RegExp("^" + name + "=(.*)$", "m"));
    return m ? m[1].trim() : "";
  } catch (e) {
    return "";
  }
}

const apiBase = process.env.API_BASE_URL || "";
const accessKey = process.env.ACCESS_KEY || valueFromDotenv("ACCESS_KEY");

const out =
  "/* AUTO-GENERATED by build-config.js - do not edit or commit. */\n" +
  "window.APP_CONFIG = {\n" +
  "  API_BASE_URL: " + JSON.stringify(apiBase) + ",\n" +
  "  ACCESS_KEY: " + JSON.stringify(accessKey) + "\n" +
  "};\n";

fs.writeFileSync(path.join(__dirname, "config.js"), out);
console.log(
  "Wrote frontend/config.js (API_BASE_URL=" +
    (apiBase || "(same origin)") +
    ", key " +
    (accessKey ? "set" : "MISSING") +
    ")"
);
