services:
  - type: web
    name: yt-app-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ACCESS_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: 10080
